"""empty message

Revision ID: d8d9e3934943
Revises: 22aa8072d705
Create Date: 2017-04-04 09:59:26.735793

"""

# revision identifiers, used by Alembic.
revision = 'd8d9e3934943'
down_revision = '22aa8072d705'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playbooks', sa.Column('meta_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playbooks', 'meta_data')
    # ### end Alembic commands ###
